name: "Homebox"
description: "Homebox is the inventory and organization system built for the Home User!"
version: "v0.10.1"
slug: "homebox"
init: false
boot: auto
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
ingress: true
ingress_port: 7745
url: "https://hay-kot.github.io/homebox/"
ports:
  7745/tcp: 3100
map:
  - config:rw